# Importing Libraries

In [ ]:
from google.colab import drive
drive.mount("//content//gdrive", force_remount=True)
url_path='/content/gdrive/MyDrive/Dataset/Placement_Data_Full_Class.csv'

Mounted at //content//gdrive


In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv(url_path)

In [ ]:
df.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

# Understanding data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   sl_no           215 non-null    int64  
 1   gender          215 non-null    object 
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object 
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object 
 6   hsc_s           215 non-null    object 
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object 
 9   workex          215 non-null    object 
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object 
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object 
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB


In [ ]:
df.describe()

sl_no       ssc_p       hsc_p    degree_p     etest_p       mba_p  \
count  215.000000  215.000000  215.000000  215.000000  215.000000  215.000000   
mean   108.000000   67.303395   66.333163   66.370186   72.100558   62.278186   
std     62.209324   10.827205   10.897509    7.358743   13.275956    5.833385   
min      1.000000   40.890000   37.000000   50.000000   50.000000   51.210000   
25%     54.500000   60.600000   60.900000   61.000000   60.000000   57.945000   
50%    108.000000   67.000000   65.000000   66.000000   71.000000   62.000000   
75%    161.500000   75.700000   73.000000   72.000000   83.500000   66.255000   
max    215.000000   89.400000   97.700000   91.000000   98.000000   77.890000   

              salary  
count     148.000000  
mean   288655.405405  
std     93457.452420  
min    200000.000000  
25%    240000.000000  
50%    265000.000000  
75%    300000.000000  
max    940000.000000

# Encoding and Transforming

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
df['gender'] = le.fit_transform(df['gender'])

In [ ]:
df['ssc_b'] = le.fit_transform(df['ssc_b'])
df['hsc_b'] = le.fit_transform(df['hsc_b'])
df['hsc_s'] = le.fit_transform(df['hsc_s'])
df['degree_t'] = le.fit_transform(df['degree_t'])
df['specialisation'] = le.fit_transform(df['specialisation'])
df['status'] = le.fit_transform(df['status'])

In [ ]:
df['workex'] = le.fit_transform(df['workex'])

In [ ]:
df['salary']= df['salary'].fillna(df['salary'].mean())

# Modeling The Data

In [ ]:
X = df.drop('status',axis=1)
y = df['status']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3, random_state=7)

# Model - 1 Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, mean_absolute_error,mean_squared_error,confusion_matrix,classification_report

In [ ]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred = model.predict(X_test)
print(f"Confusion Matrix is: \n {confusion_matrix(y_test,y_pred)}\n\n\n")
print(f"Classification Report is \n: {classification_report(y_test,y_pred)}\n\n\n")
print(f"Accuraccy Precent is: \n {accuracy_score(y_test,y_pred)*100}\n\n\n")

Confusion Matrix is: 
 [[10 10]
 [ 5 40]]



Classification Report is 
:               precision    recall  f1-score   support

           0       0.67      0.50      0.57        20
           1       0.80      0.89      0.84        45

    accuracy                           0.77        65
   macro avg       0.73      0.69      0.71        65
weighted avg       0.76      0.77      0.76        65




Accuraccy Precent is: 
 76.92307692307693





# Model - 2 Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model = RandomForestClassifier()
model.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred = model.predict(X_test)
print(f"Confusion Matrix is: \n {confusion_matrix(y_test,y_pred)}\n\n\n")
print(f"Classification Report is \n: {classification_report(y_test,y_pred)}\n\n\n")
print(f"Accuraccy Precent is: \n {accuracy_score(y_test,y_pred)*100}\n\n\n")

Confusion Matrix is: 
 [[14  6]
 [ 1 44]]



Classification Report is 
:               precision    recall  f1-score   support

           0       0.93      0.70      0.80        20
           1       0.88      0.98      0.93        45

    accuracy                           0.89        65
   macro avg       0.91      0.84      0.86        65
weighted avg       0.90      0.89      0.89        65




Accuraccy Precent is: 
 89.23076923076924





# Model - 3 Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model = DecisionTreeClassifier()
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = model.predict(X_test)
print(f"Confusion Matrix is: \n {confusion_matrix(y_test,y_pred)}\n\n\n")
print(f"Classification Report is \n: {classification_report(y_test,y_pred)}\n\n\n")
print(f"Accuraccy Precent is: \n {accuracy_score(y_test,y_pred)*100}\n\n\n")

Confusion Matrix is: 
 [[20  0]
 [ 2 43]]



Classification Report is 
:               precision    recall  f1-score   support

           0       0.91      1.00      0.95        20
           1       1.00      0.96      0.98        45

    accuracy                           0.97        65
   macro avg       0.95      0.98      0.96        65
weighted avg       0.97      0.97      0.97        65




Accuraccy Precent is: 
 96.92307692307692





# Model - 4 KNeighbor(KNN)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model = KNeighborsClassifier()
model.fit(X_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred = model.predict(X_test)
print(f"Confusion Matrix is: \n {confusion_matrix(y_test,y_pred)}\n\n\n")
print(f"Classification Report is \n: {classification_report(y_test,y_pred)}\n\n\n")
print(f"Accuraccy Precent is: \n {accuracy_score(y_test,y_pred)*100}\n\n\n")

Confusion Matrix is: 
 [[20  0]
 [ 2 43]]



Classification Report is 
:               precision    recall  f1-score   support

           0       0.91      1.00      0.95        20
           1       1.00      0.96      0.98        45

    accuracy                           0.97        65
   macro avg       0.95      0.98      0.96        65
weighted avg       0.97      0.97      0.97        65




Accuraccy Precent is: 
 96.92307692307692





# Model - 5 Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
model = GaussianNB()
model.fit(X_train,y_train)

GaussianNB()

In [ ]:
y_pred = model.predict(X_test)
print(f"Confusion Matrix is: \n {confusion_matrix(y_test,y_pred)}\n\n\n")
print(f"Classification Report is \n: {classification_report(y_test,y_pred)}\n\n\n")
print(f"Accuraccy Precent is: \n {accuracy_score(y_test,y_pred)*100}\n\n\n")

Confusion Matrix is: 
 [[20  0]
 [ 0 45]]



Classification Report is 
:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       1.00      1.00      1.00        45

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65




Accuraccy Precent is: 
 100.0



